apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: apdev-eks-cluster
  region: ap-northeast-2
  version: "1.35"

vpc:
  id: vpc-064c4c1ab1b359a6d
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-03da97efda566503c
      ap-northeast-2b:
        id: subnet-0790e7e0f3368ada1
    public:
      ap-northeast-2a:
        id: subnet-0bff78876055bf216
      ap-northeast-2b:
        id: subnet-078e4f754f7337134

managedNodeGroups:
  - name: apdev-ng
    instanceType: t3.medium  # ← 대회 당일 변경
    amiFamily: Bottlerocket
    minSize: 1
    maxSize: 4
    desiredCapacity: 1
    volumeSize: 20
    volumeType: gp3
    privateNetworking: true
    labels:
      role: worker
    tags:
      Name: apdev-node
    bottlerocket:
      settings:
        kubernetes:
          maxPods: 58
          systemReserved:
            cpu: "50m"
            memory: "256Mi"
          kubeReserved:
            cpu: "50m"
            memory: "256Mi"
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true

iam:
  withOIDC: true
