apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: apdev
data:
  AWS_REGION: "${region}"
  MYSQL_DBNAME: "${db_name}"
  MYSQL_HOST: "${db_host}"
  MYSQL_PASSWORD: "${db_pass}"
  MYSQL_PORT: "${db_port}"
  MYSQL_USER: "${db_user}"
  S3_BUCKET: "${s3_bucket}"
